const Map<String, String> orderStatuses = {
  'PENDING': 'PENDING',
  'ACCEPTED': 'ACCEPTED',
  'SEARCHING_DRIVER': 'SEARCHING_DRIVER',
  'DRIVER_FOUND': 'DRIVER_FOUND',
  'ON_THE_WAY_TO_VENDOR': 'ON_THE_WAY_TO_VENDOR',
  'AT_VENDOR': 'AT_VENDOR',
  'ON_THE_WAY_TO_CUSTOMER': 'ON_THE_WAY_TO_CUSTOMER',
  'DELIVERED': 'DELIVERED',
  'CANCELED': 'CANCELED',
  'DRAFT': 'DRAFT',
};
