// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcUtn_QtgqRKZ9Sw3ddLglOhM9nagpLEQ',
    appId: '1:890873103309:web:4e99c779cedf6d3ac2ba84',
    messagingSenderId: '890873103309',
    projectId: 'cendikiawanstudiosindragiri',
    authDomain: 'cendikiawanstudiosindragiri.firebaseapp.com',
    storageBucket: 'cendikiawanstudiosindragiri.firebasestorage.app',
    measurementId: 'G-DP3V0KTPYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIkBlsQ24fNun7edrRA2fFaKkHrAIN_c4',
    appId: '1:890873103309:android:05724dfe1345e437c2ba84',
    messagingSenderId: '890873103309',
    projectId: 'cendikiawanstudiosindragiri',
    storageBucket: 'cendikiawanstudiosindragiri.firebasestorage.app',
  );
}
